FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

COPY app ./
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
RUN ls
EXPOSE 80
ENTRYPOINT ["dotnet", "app.dll"]
ENV FIRST_NAME=FirstName
ENV LAST_NAME=LastName